dist: trusty
sudo: required
language: cpp

# build matrix

os: 
    - osx
    - linux
    
compiler: 
    - g++ 
    - clang

env: 
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix: 
    exclude: 
        os: osx
        compiler: g++

before_install: 
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install qt cmake; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install cmake qtbase5-dev; fi

install: 
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - make
